name: Test @airnode packages

on: push

jobs:
  build:
    name: Run Linting and Tests

    runs-on: ubuntu-latest

    steps:
    - name: Clone airnode
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Dependencies
      run: npm run bootstrap

    - name: Lint code
      run: npm run lint

    - name: Build
      run: |
        npm run build:contracts
        npm run build:ois
        npm run build:adapter

    - name: Test adapter
      run: npm run test:adapter

    - name: Test contracts
      run: npm run test:contracts

    - name: Test node
      run: npm run test:node

    - name: Prepare config
      run: |
        cp packages/node/config.json.example packages/node/config.json
        cp packages/node/security.json.example packages/node/security.json

    - name: Build node
      run: npm run build:node

